# Generated by Django 3.1.7 on 2021-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
